project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Seyoon Ko"

  page-footer:
    left: "&copy; Copyright 2024, Seyoon Ko"
    right: "This page is built with [Quarto](https://quarto.org/)."

  sidebar:
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    contents:

      # - text: "Research"
      #   href: research/index.qmd
  
      - text: "Publications"
        href: publications/index.qmd
      
      - text: "Teaching"
        href: teaching/index.qmd
        
      - text: "Software"
        href: software/index.qmd

      - text: "About"
        href: about.qmd
        
      - text: "CV"
        href: cv.qmd
        
#      - text: "Blog"
#        href: blog.qmd


      # - section: "About"
      #   contents:
      #     - text: "About me"
      #       href: about.qmd
      #     - text: "This template"
      #       href: about_template.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


